version: "3.9"

services:
  frontend:
    image: ${DOCKERHUB_USER}/php-frontend:${BUILD_NUMBER}
    ports:
      - "8081:80"
    depends_on:
      - backend

  backend:
    image: ${DOCKERHUB_USER}/php-backend:${BUILD_NUMBER}
    ports:
      - "8082:80"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpass
      - DB_NAME=appdb
    depends_on:
      db:
        condition: service_started

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
